<a href="https://colab.research.google.com/github/lewyspharoah94-spec/Ai-MLUni/blob/main/Week%202%20Challenge%201%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas  exercise for Level 4

## 1. Setup

### Import

Before moving on to learn pandas first we need to install it and import it. If you install [Anaconda distributions](https://www.anaconda.com/) on your local machine or using [Google Colab](https://research.google.com/colaboratory) then pandas will already be available there, otherwise, you follow this installation process from [pandas official's website](https://pandas.pydata.org/docs/getting_started/install.html).

In [20]:
# Importing libraries
import numpy as np
import pandas as pd

In [21]:
# we can set numbers for how many rows and columns will be displayed
pd.set_option('display.min_rows', 10) #default will be 10
pd.set_option('display.max_columns', 20)

## 2. Loading Different Data Formats Into a Pandas Data Frame

### Reading CSV file

In [37]:
# read csv file

url='https://raw.githubusercontent.com/tdmhub/L4DA_resources/main/online_store_customer_data.csv'
df = df = pd.read_csv(url,delimiter=',')
df

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
0,01/01/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36
1,01/01/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04
2,01/01/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60
3,01/01/2019,151203,NaN,18.0,Single,Virginia,Platinum,workers,Card,1.0,1199.79
4,01/01/2019,151204,Male,27.0,Single,Connecticut,Basic,self-employed,Card,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2507,05/01/2021,153695,Female,57.0,Single,South Carolina,Platinum,self-employed,Card,0.0,150.10
2508,05/01/2021,153696,Female,36.0,Married,Hawaii,Silver,self-employed,PayPal,1.0,708.88
2509,05/01/2021,153697,Male,22.0,Single,South Carolina,Basic,workers,PayPal,1.0,2030.07
2510,05/01/2021,153698,NaN,44.0,Single,New York,Basic,Employees,PayPal,0.0,1909.77
2511,05/01/2021,153699,Male,48.0,Single,California,Silver,workers,PayPal,1.0,1073.15

Exercises

Question 1 : Display the first 3 rows

In [44]:
# Question 1 display first 3 rows
df.head(3)

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
0,01/01/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36
1,01/01/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04
2,01/01/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60

Question 2 : Display the last 10 rows

In [24]:
# display last 10 rows

Question 3 : Display the datatypes of the dataset

In [25]:
# Display the datatype of the dataset

Question 4: Display all the column names within the dataset

In [26]:
#Display the column names

Question 5 : Display the 5nd to 11th rows within the dataset

In [27]:
#for display 5nd to 11th rows

Question 6 : Remove the referal column from the dataset.

In [28]:
#Drop 	"Referal" unwanted column

Question 7 : Create a new dataframe and then rename the column "Amount_spent" to payment

In [29]:
# create new df_col dataframe from df.copy() method.


# rename column name  Amount_spent to payment

Question 8 : Add a new payment_pounds column which value will convert dollar amount into pounds  based on the following exchnage rate ( 1 Dollar to 0.80 Pounds)

In [30]:
# Add a new payment_pounds column which value will convert dollar amount into pounds

In [31]:
#Check the new values

Question 9 : Find out how many duplicate rows there are.

In [32]:
# Display duplicated entries

Question 10 : Remove all of the duplicated rows from the dataset

Question 11 : Display missing value count and sort them least to most

In [33]:
# Display missing value count and sort them least to most

Question 12 : Delete all records that have a Nan in the Gender column.

In [34]:
#Delete all records that have a Nan in the referal column.

Questions 13 : Change all Nan from the column "Amount_Spent" to the mean value of that column.

In [35]:
# Imput Mean in all Nan values from Amount_Spent column